### ISSUE TITLE
Le message de confirmation/erreur ne disparaît pas 

### ISSUE THREAD

**Issue by jerrywham** [timovn/oText#4]
Lors de l'enregistrement ou de l'édition d'un article, le message de confirmation de l'enregistrement ne disparaît pas et le bloc ayant la classe `.confirmation` prend toute la hauteur de l'écran et masque les champs du formulaire.
Peut être corrigé avec le css suivant, fichier `admin/style/styles/style-styles.css` ligne 358 ~
```css
/* Message de confirmation ou d’erreur */
.confirmation, .no_confirmation {
	max-width: 400px; max-height: 200px;
	position: fixed;
	top: 0; left: 20px;
	padding: 15px;
	margin: auto;
	text-align: center;
	font-weight: bold;
	z-index: 150;
	box-shadow: 0px 2px 24px 0px rgba(0, 0, 0, 0.2);
	animation: popup-disapear 7s;
	animation-fill-mode: forwards;
	border: 1px solid #333;
	border-radius: 3px;
	background: #444;
	color: #fff;
}
```
